//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUANCAFE_Nhom3.Module.BusinessObjects.ORMDataModel2
{

    [DefaultProperty("Nam")]
    public partial class Bangluong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvienID;
        [Association(@"BangluongReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        DateTime fNam;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Nam
        {
            get { return fNam; }
            set { SetPropertyValue<DateTime>(nameof(Nam), ref fNam, value); }
        }
        DateTime fThang;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Thang
        {
            get { return fThang; }
            set { SetPropertyValue<DateTime>(nameof(Thang), ref fThang, value); }
        }
        double fSogioLam;
        public double SogioLam
        {
            get { return fSogioLam; }
            set { SetPropertyValue<double>(nameof(SogioLam), ref fSogioLam, value); }
        }
        [PersistentAlias("ToDecimal([SogioLam]) * [Mucluong]")]
        public string Luong
        {
            get { return (string)(EvaluateAlias(nameof(Luong))); }
        }
    }

}
