//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUANCAFE_Nhom3.Module.BusinessObjects.ORMDataModel2
{

    [DefaultProperty("Soluong")]
    public partial class DongNhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Sanpham fSanphamID;
        [Association(@"DongNhapReferencesSanpham")]
        public Sanpham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<Sanpham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        PhieuNhap fNhapID;
        [Association(@"DongNhapReferencesPhieuNhap")]
        public PhieuNhap NhapID
        {
            get { return fNhapID; }
            set { SetPropertyValue<PhieuNhap>(nameof(NhapID), ref fNhapID, value); }
        }
        string fSoluong;
        public string Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<string>(nameof(Soluong), ref fSoluong, value); }
        }
        string fDongia;
        public string Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<string>(nameof(Dongia), ref fDongia, value); }
        }
    }

}
