//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUANCAFE_Nhom3.Module.BusinessObjects.ORMDataModel2
{

    [DefaultProperty("So")]
    public partial class PhieuNhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNCCID;
        public string NCCID
        {
            get { return fNCCID; }
            set { SetPropertyValue<string>(nameof(NCCID), ref fNCCID, value); }
        }
        string fNhanvienID;
        public string NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<string>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        string fSo;
        public string So
        {
            get { return fSo; }
            set { SetPropertyValue<string>(nameof(So), ref fSo, value); }
        }
        string fNgay;
        public string Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<string>(nameof(Ngay), ref fNgay, value); }
        }
    }

}
